version: '3.7'

services:
  reverse-proxy:
    container_name: django-doh.reverse-proxy
    build:
      context: dev
      dockerfile: dev/Dockerfile-nginx
    image: django-doh/reverse-proxy
    ports:
     - 443:443
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - doh-server

  doh-server:
    container_name: django-doh.doh-server
    build:
      context: dev
      dockerfile: dev/Dockerfile-server
    image: django-doh/doh-server
    ports:
      - 8000:8000
    volumes:
      - .:/src
    command: pipenv run python manage.py runserver 0:8000 --settings=django_doh.settings
